### ISSUE TITLE
Typescript compiler 'unused file' warnings

### ISSUE THREAD

**Issue by kdumontnu** [maximegris/angular-electron#461]
In latest master I get a number of warnings from the typescript compiler for unused files.

```
WARNING in ...\angular-electron\main.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in ...\angular-electron\src\polyfills-test.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in ...\angular-electron\src\test.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in ...\angular-electron\src\environments\environment.dev.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in ...\angular-electron\src\environments\environment.prod.ts is part of the 
TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in ...\angular-electron\src\environments\environment.web.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

Changing `tsconfig.json` from:
```
  "include": [
    "main.ts",
    "src/**/*"
  ],
```
to:
```
  "files": [
      "src/main.ts",
      "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ],
```
and `tsconfig-serve.json` from:
```
  "include": [
    "main.ts"
  ],
```
to:
```
  "files": [
      "main.ts",
  ],
```
per the recommendations here: https://github.com/angular/angular-cli/issues/15626
Seems to clean things up for me. 

I'm happy to create a PR if it helps.

**Comment by maximegris** [comment]
Thanks @kdumontnu  for this report. I pushed your fix

**Comment by distributev** [comment]
This is still happening when I run

npm run start

![image](https://user-images.githubusercontent.com/19224635/89641989-2afa1700-d8b3-11ea-8247-85caef00c295.png)
