### ISSUE TITLE
Getting Parsing Error in main.ts after updating

### ISSUE THREAD

**Issue by Rajdeep97** [maximegris/angular-electron#502]
When I open the main.ts file(the file which acts as the host for everything), I get this error:

Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: main.ts.
The file must be included in at least one of the projects provided.

Can someone please point towards how I can resolve this error?
Thanks!

**Comment by Rajdeep97** [comment]
Weirdly after adding the file(main.ts) explicitly in .eslintrc.json :

```
      "parser": "@typescript-eslint/parser",
      "parserOptions": {
        "ecmaVersion": 10,
        "project": [
          **"main.ts",**
          "./src/tsconfig.app.json",
          "./src/tsconfig.spec.json",
          "./e2e/tsconfig.e2e.json"
        ],
        "sourceType": "module",
        "ecmaFeatures": {
            "modules": true
        }
      }, 
```
and reloading the window in vs-code, the problem disappeared.

Is anyone else facing this problem?
Then, I might ask the author to include this lin in the file.

Alternatively, are there any side effects of doing this?

**Comment by Rajdeep97** [comment]
Doing the above thing I mentioned, takes away the error from main.ts file, but create a new error of "unable to parse" in app.module.ts.
Hence, I am back to square one.

Anyone has any leads how I can solve this?

**Comment by mikaeljensen** [comment]
I have the same problem and have not found a good solution. So I just ignore it for now, as it does not break anything

**Comment by Rajdeep97** [comment]
I found a temporary solution for this, which is working for me:

Add a file '.eslintignore' in the root directory of the project, containing:
`main.ts`

Incase @mikaeljensen, you are facing this problem you can use this as temporary fix.

@maximegris Can you please look into this.
If my solution works, can you please include this as a file in this project.

**Comment by maximegris** [comment]
You can add `./tsconfig-serve.json` in `parserOptions.project` section in `.eslintrc.json`. This should fix the issue in your IDE.

```      
[...]
"parserOptions": {
        "ecmaVersion": 10,
        "project": [
          "./tsconfig-serve.json",
          "./src/tsconfig.app.json",
          "./src/tsconfig.spec.json",
          "./e2e/tsconfig.e2e.json"
        ],
        "sourceType": "module",
        "ecmaFeatures": {
            "modules": true
        }
      }
[...]
```

**Comment by tobysmith568** [comment]
Hey @maximegris , I'm also getting this error and your suggestion has not fixed it for me :/

I actually only used your template yesterday, so I already had your suggestion as I see you added it in:
https://github.com/maximegris/angular-electron/commit/4b17ab64e628459c24b69cb8a82da8dcc09dc501

For me, the error is not in my `main.ts`, but is in a `whatever.interface.ts` file that I have added within my `src`.
Any help would be great :)
